services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    env_file: ./config/minio.env
    ports: 
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes: 
      - minio-volume:/data
    networks:
      - airflow_learning_default
volumes:
  minio-volume:
networks:
  airflow_learning_default:
    external: True

