FROM ubuntu:24.04

WORKDIR /usr/local/my_work

RUN apt update -y && \
apt install nano -y && \
apt install python3 -y && \
apt install python3-pip -y 

RUN apt install python3-venv -y
#RUN pip install pyspark
