version: '3.8'

services:
  spark-master:
    image: apache/spark:python3
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"
      - "8081:8081"
      - "4040:4040"
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8081
      - SPARK_PUBLIC_DNS=localhost
    volumes:
      - ./app:/opt/spark-app
      - ./data:/opt/spark-data
    networks:
      - spark-net

  spark-worker:
    image: apache/spark:python3
    container_name: spark-worker
    depends_on:
      - spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    ports:
      - "8082:8082"
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_WEBUI_PORT=8082
      - SPARK_PUBLIC_DNS=localhost
    volumes:
      - ./app:/opt/spark-app
      - ./data:/opt/spark-data
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge
