services:
  spark-gpt:
    build: .
    container_name: spark-gpt
    command: >
      bash -c "
      /opt/spark/bin/spark-submit
      --packages org.apache.spark:spark-connect_2.12:3.5.1
      --class org.apache.spark.sql.connect.service.SparkConnectService
      --conf spark.connect.grpc.binding.port=15002
      --conf spark.connect.grpc.binding.host=0.0.0.0
      --conf spark.driver.bindAddress=0.0.0.0
      spark-internal
      "
    restart: unless-stopped
    ports:
      - "15002:15002"
    networks:
      - 20d181f6536f
networks:
  20d181f6536f:
    external: True
